server:
    port: 8886

apache:
    rocketmq:
        nameserverAdder: 127.0.0.1:9876
        producer:
            producerFroup: producerGroup
            topic: feipruducer
        consumer:
            PushConsumer: consumer
            topic: feiconsumer
spring:
    redis:
        host: 127.0.0.1
        port: 6379
        database: 0
        pool:
            max-active: 20
            max-wait: 5000
            max-idle: 10
            min-idle: 2
        timeout: 6000
        expires:
            cache: 10000

    application:
        name: afei
    datasource:
        url: jdbc:mysql://localhost:3306/pdman?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=true&verifyServerCertificate=false&allowMultiQueries=true
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: root
        type: com.alibaba.druid.pool.DruidDataSource

mybatis:
    mapper-locations: classpath*:mapper/*/*.xml
    type-aliases-package: com.afei.pojo.*

